---

services:
  app:
    build: .
    environment:
      - CAS_LOGIN_URL=https://auth.berkeley.edu/cas/
      - CAS_VALIDATE_URL=https://auth.berkeley.edu/cas/serviceValidate
      - CAS_PROXY_VALIDATE_URL=https://auth.berkeley.edu/cas/proxyValidate
      - CAS_ROOT_PROXIED_AS=http://localhost
    ports:
      - 80:80
    volumes:
      - ./data/pa_symlinks:/srv/pa_symlinks:ro
      - /data/pa:/srv/pa:ro